<a href="https://colab.research.google.com/github/KawshalRam/Scikit-Learn/blob/main/2)_scikit_learn_Feature_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv('/content/drive/MyDrive/CAR DETAILS FROM CAR DEKHO.csv')

In [ ]:
df

name  year  selling_price  km_driven  \
0                           Maruti 800 AC  2007          60000      70000   
1                Maruti Wagon R LXI Minor  2007         135000      50000   
2                    Hyundai Verna 1.6 SX  2012         600000     100000   
3                  Datsun RediGO T Option  2017         250000      46000   
4                   Honda Amaze VX i-DTEC  2014         450000     141000   
...                                   ...   ...            ...        ...   
4335  Hyundai i20 Magna 1.4 CRDi (Diesel)  2014         409999      80000   
4336           Hyundai i20 Magna 1.4 CRDi  2014         409999      80000   
4337                  Maruti 800 AC BSIII  2009         110000      83000   
4338     Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000   
4339                     Renault KWID RXT  2016         225000      40000   

        fuel seller_type transmission         owner  
0     Petrol  Individual       Manual   First Owner  
1     Petrol  Individual       Manual   First Owner  
2     Diesel  Individual       Manual   First Owner  
3     Petrol  Individual       Manual   First Owner  
4     Diesel  Individual       Manual  Second Owner  
...      ...         ...          ...           ...  
4335  Diesel  Individual       Manual  Second Owner  
4336  Diesel  Individual       Manual  Second Owner  
4337  Petrol  Individual       Manual  Second Owner  
4338  Diesel  Individual       Manual   First Owner  
4339  Petrol  Individual       Manual   First Owner  

[4340 rows x 8 columns]

In [ ]:
df=df[['selling_price','km_driven','year']]

In [ ]:
df

selling_price  km_driven  year
0             60000      70000  2007
1            135000      50000  2007
2            600000     100000  2012
3            250000      46000  2017
4            450000     141000  2014
...             ...        ...   ...
4335         409999      80000  2014
4336         409999      80000  2014
4337         110000      83000  2009
4338         865000      90000  2016
4339         225000      40000  2016

[4340 rows x 3 columns]

# Applying Normalization : Minmax Scaling

---


why we need to feature scale: so that all the columns have similar weightag/values of all the variables are to a similar scale

MinMax Scaling results in the range of 0 and 1. Also known as Normalization

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler=MinMaxScaler()

In [ ]:
scald_df=scaler.fit_transform(df)

In [ ]:
scald_df

array([[0.0045045 , 0.08678301, 0.53571429],
       [0.01295045, 0.06198751, 0.53571429],
       [0.06531532, 0.12397626, 0.71428571],
       ...,
       [0.01013514, 0.10290008, 0.60714286],
       [0.09515766, 0.11157851, 0.85714286],
       [0.02308559, 0.04958976, 0.85714286]])

In [ ]:
scald_df=pd.DataFrame(data=scald_df,columns=df.columns)

In [ ]:
scald_df

selling_price  km_driven      year
0          0.004505   0.086783  0.535714
1          0.012950   0.061988  0.535714
2          0.065315   0.123976  0.714286
3          0.025901   0.057028  0.892857
4          0.048423   0.174807  0.785714
...             ...        ...       ...
4335       0.043919   0.099181  0.785714
4336       0.043919   0.099181  0.785714
4337       0.010135   0.102900  0.607143
4338       0.095158   0.111579  0.857143
4339       0.023086   0.049590  0.857143

[4340 rows x 3 columns]

Train Test Split

In [ ]:
df

selling_price  km_driven  year
0             60000      70000  2007
1            135000      50000  2007
2            600000     100000  2012
3            250000      46000  2017
4            450000     141000  2014
...             ...        ...   ...
4335         409999      80000  2014
4336         409999      80000  2014
4337         110000      83000  2009
4338         865000      90000  2016
4339         225000      40000  2016

[4340 rows x 3 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=df.drop('selling_price',axis=1)
y=df['selling_price']

In [ ]:
x

km_driven  year
0         70000  2007
1         50000  2007
2        100000  2012
3         46000  2017
4        141000  2014
...         ...   ...
4335      80000  2014
4336      80000  2014
4337      83000  2009
4338      90000  2016
4339      40000  2016

[4340 rows x 2 columns]

In [ ]:
y

0        60000
1       135000
2       600000
3       250000
4       450000
         ...  
4335    409999
4336    409999
4337    110000
4338    865000
4339    225000
Name: selling_price, Length: 4340, dtype: int64

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
X_train

km_driven  year
227       20000  2017
964       50000  2018
2045      25000  2013
1025      70000  2011
4242      72000  2017
...         ...   ...
3444      50000  2006
466       80000  2011
3092      51000  2016
3772      80000  2013
860       80000  2013

[3472 rows x 2 columns]

In [ ]:
X_train_scald=scaler.fit_transform(X_train)
X_test_scald=scaler.transform(X_test)

In [ ]:
X_train_scald

array([[0.02479426, 0.89285714],
       [0.06198751, 0.92857143],
       [0.03099313, 0.75      ],
       ...,
       [0.06322728, 0.85714286],
       [0.09918076, 0.75      ],
       [0.09918076, 0.75      ]])

In [ ]:
X_train_scald_pd=pd.DataFrame(data=X_train_scald,columns=X_train.columns)

In [ ]:
X_train_scald_pd

km_driven      year
0      0.024794  0.892857
1      0.061988  0.928571
2      0.030993  0.750000
3      0.086783  0.678571
4      0.089263  0.892857
...         ...       ...
3467   0.061988  0.500000
3468   0.099181  0.678571
3469   0.063227  0.857143
3470   0.099181  0.750000
3471   0.099181  0.750000

[3472 rows x 2 columns]

In [ ]:
Y_train_scaldpd=scaler.fit_transform(Y_train.values.reshape(-1, 1))
Y_test_scaldpd=scaler.transform(Y_test.values.reshape(-1, 1))

In [ ]:
Y_train_scaldpd

array([[0.18184055],
       [0.05880906],
       [0.00871063],
       ...,
       [0.07910925],
       [0.02817409],
       [0.01882382]])

In [ ]:
Y_train_scald_pd=pd.DataFrame(data=Y_train_scaldpd,columns=['selling_price'])

In [ ]:
Y_train_scald_pd

selling_price
0          0.181841
1          0.058809
2          0.008711
3          0.008981
4          0.081570
...             ...
3467       0.058809
3468       0.013656
3469       0.079109
3470       0.028174
3471       0.018824

[3472 rows x 1 columns]